### ISSUE TITLE
Is the user-tools Block intentionally hiding content on registration?

### ISSUE THREAD

**Issue by jtwiest** [JarvusInnovations/emergence-skeleton-v2#3]
https://github.com/JarvusInnovations/Emergence-Skeleton-v2/blob/master/html-templates/register/register.tpl#L5

@themightychris I was working on a site and found that this block was hiding the user tool and actually messed with my template since it was replacing user tools with nothing. (It isn't calling parent)

Is this block intentional ie. are you trying to remove user tools from the template on this page? If not I think this line should be removed.

**Comment by themightychris** [comment]
This was intentional so that the in-page embedded login box in the header
wouldn't be visible on the register page. The point of that embedded login
box is to log you in to whatever page you're on without leaving that page,
but that doesn't really make sense on the register page because you can't
register if you're logged in and reloading it after logging in will just
show you an error about already being registered.

On Wed, Sep 9, 2015 at 10:19 PM, Tyler Wiest <notifications@github.com>
wrote:

>
> https://github.com/JarvusInnovations/Emergence-Skeleton-v2/blob/master/html-templates/register/register.tpl#L5
>
> @themightychris <https://github.com/themightychris> I was working on a
> site and found that this block was hiding the user tool and actually messed
> with my template since it was replacing user tools with nothing. (It isn't
> calling parent)
>
> Is this block intentional ie. are you trying to remove user tools from the
> template on this page? If not I think this line should be removed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JarvusInnovations/emergence-skeleton-v2/issues/3>.
>



-- 
Chris Alfano
Chief Developer
Jarv.us Innovations <http://jarv.us>

(e) chris@jarv.us (m) 267-918-6166

**Comment by jtwiest** [comment]
Gotcha thanks.
